import { Plus, X } from "lucide-react";

const createEmptyProduct = () => ({ title: "", description: "", category: "", wholesalePrice: "", sku: "", sizes: [], isFeatured: false, isNewArrival: false, isActive: true });
const productToForm = (product = {}) => { const withoutColors = { ...product }; delete withoutColors.colors; return { ...createEmptyProduct(), ...withoutColors }; };
const buildProductForm = (product, files) => { const formData = new FormData(); ["title", "description", "category", "wholesalePrice", "sku", "isFeatured", "isNewArrival", "isActive"].forEach((field) => formData.append(field, product[field] ?? "")); formData.append("sizes", JSON.stringify(product.sizes || [])); Array.from(files || []).forEach((file) => formData.append("images", file)); return formData; };
const parseList = (value) => value.split(",").map((item) => item.trim()).filter(Boolean);
export { buildProductForm, createEmptyProduct, productToForm };

export default function AdminProductForm({ productForm, setProductForm, imageFiles, setImageFiles, editingId, loading, onSubmit, onClose }) {
  const setField = (field, value) => setProductForm((current) => ({ ...current, [field]: value }));
  return <form className="card fade-up" style={{ padding: 28 }} onSubmit={onSubmit}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 24 }}><span className="eyebrow">{editingId ? "Edit Product" : "New Product"}</span><button type="button" className="btn btn-soft" onClick={onClose}><X size={15} /> Close</button></div><div className="grid grid-2">{["title", "category", "sku", "wholesalePrice"].map((field) => <div className="field" key={field}><label>{field === "sku" ? "SKU" : field === "wholesalePrice" ? "Wholesale Price" : field[0].toUpperCase() + field.slice(1)}</label><input className="input" required type={field === "wholesalePrice" ? "number" : "text"} min={field === "wholesalePrice" ? "0" : undefined} value={productForm[field] ?? ""} onChange={(event) => setField(field, event.target.value)} /></div>)}<div className="field"><label>Sizes (comma separated)</label><input className="input" placeholder="S, M, L, XL" value={(productForm.sizes || []).join(", ")} onChange={(event) => setField("sizes", parseList(event.target.value))} /></div><div className="field" style={{ gridColumn: "1 / -1" }}><label>Description</label><textarea className="textarea" value={productForm.description} onChange={(event) => setField("description", event.target.value)} /></div><div className="field" style={{ gridColumn: "1 / -1" }}><label>Product Images</label><input className="input" type="file" multiple accept="image/png,image/jpeg,image/jpg,image/webp" onChange={(event) => setImageFiles(event.target.files)} />{imageFiles.length > 0 && <small>{imageFiles.length} image(s) ready to upload</small>}</div></div><div style={{ display: "flex", gap: 16, margin: "24px 0 18px", flexWrap: "wrap" }}>{[["isActive", "Active"], ["isFeatured", "Featured"], ["isNewArrival", "New Arrival"]].map(([field, label]) => <label key={field} style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 13 }}><input type="checkbox" checked={Boolean(productForm[field])} onChange={(event) => setField(field, event.target.checked)} />{label}</label>)}</div><button className="btn btn-primary" disabled={loading}><Plus size={16} /> {loading ? "Saving..." : editingId ? "Update Product" : "Create Product"}</button></form>;
}
