const Category = require("../Models/Category");
const Product = require("../Models/Product");
const cloudinary = require("../Config/cloudinaryConfig");
const slugify = require("slugify");

const active = (value, fallback = true) => value === undefined ? fallback : String(value).toLowerCase() === "true";
async function uniqueSlug(name, id) { const base = slugify(name, { lower: true, strict: true }) || "category"; let slug = base; let number = 2; while (await Category.exists({ slug, ...(id ? { _id: { $ne: id } } : {}) })) slug = `${base}-${number++}`; return slug; }
function uploadImage(buffer) { return new Promise((resolve, reject) => cloudinary.uploader.upload_stream({ folder: "raj-haksh/categories", resource_type: "image" }, (error, result) => error ? reject(error) : resolve(result.secure_url)).end(buffer)); }

async function GetCategories(req, res) { try { const query = req.query.includeInactive === "true" && req.role === "admin" ? {} : { isActive: true }; const categories = await Category.find(query).sort({ name: 1 }); return res.json({ success: true, categories }); } catch { return res.status(500).json({ success: false, message: "Unable to fetch categories" }); } }
async function GetCategory(req, res) { try { const category = await Category.findOne({ slug: req.params.slug, isActive: true }); if (!category) return res.status(404).json({ success: false, message: "Category not found" }); return res.json({ success: true, category }); } catch { return res.status(500).json({ success: false, message: "Unable to fetch category" }); } }
async function CreateCategory(req, res) { try { const name = String(req.body.name || "").trim(); if (!name) return res.status(400).json({ success: false, message: "Category name is required" }); const image = req.file ? await uploadImage(req.file.buffer) : ""; const category = await Category.create({ name, slug: await uniqueSlug(name), description: String(req.body.description || "").trim(), image, isActive: active(req.body.isActive) }); return res.status(201).json({ success: true, message: "Category created successfully", category }); } catch (error) { if (error.code === 11000) return res.status(409).json({ success: false, message: "Category already exists" }); return res.status(500).json({ success: false, message: "Unable to create category" }); } }
async function UpdateCategory(req, res) { try { const category = await Category.findById(req.params.id); if (!category) return res.status(404).json({ success: false, message: "Category not found" }); const name = String(req.body.name || category.name).trim(); if (!name) return res.status(400).json({ success: false, message: "Category name is required" }); if (name !== category.name) { category.name = name; category.slug = await uniqueSlug(name, category._id); } category.description = String(req.body.description ?? category.description).trim(); if (req.body.isActive !== undefined) category.isActive = active(req.body.isActive); if (req.file) category.image = await uploadImage(req.file.buffer); await category.save(); return res.json({ success: true, message: "Category updated successfully", category }); } catch { return res.status(500).json({ success: false, message: "Unable to update category" }); } }
async function DeleteCategory(req, res) { try { const category = await Category.findById(req.params.id); if (!category) return res.status(404).json({ success: false, message: "Category not found" }); const products = await Product.exists({ category: category.name, isActive: true }); if (products) { category.isActive = false; await category.save(); return res.json({ success: true, message: "Category deactivated because it has products", category }); } await category.deleteOne(); return res.json({ success: true, message: "Category deleted successfully" }); } catch { return res.status(500).json({ success: false, message: "Unable to delete category" }); } }
module.exports = { GetCategories, GetCategory, CreateCategory, UpdateCategory, DeleteCategory };
