const User = require("../Models/User");
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");
const { accessCookieOptions, refreshCookieOptions, cookieBaseOptions } = require("../Config/cookieConfig");
const safeUser = "-password -resetPasswordToken -resetPasswordExpire";
const validEmail = (email) => /^\S+@\S+\.\S+$/.test(String(email || ""));
const issueTokens = (res, user) => { const payload = { id: user._id, role: user.role }; res.cookie("accessToken", jwt.sign(payload, process.env.ACCESS, { expiresIn: "30m" }), accessCookieOptions()); res.cookie("refreshToken", jwt.sign(payload, process.env.REFRESH, { expiresIn: "7d" }), refreshCookieOptions()); };

async function SignUp(req, res) { try { const { name, password, phone } = req.body; const email = String(req.body.email || "").trim().toLowerCase(); if (!String(name || "").trim() || !validEmail(email) || String(password || "").length < 6) return res.status(400).json({ success: false, message: "Name, valid email and a 6 character password are required" }); if (await User.exists({ email })) return res.status(409).json({ success: false, message: "User already exists" }); await User.create({ name: name.trim(), email, phone: String(phone || "").trim(), password: await bcrypt.hash(password, 10), role: "customer" }); return res.status(201).json({ success: true, message: "Registration successful" }); } catch { return res.status(500).json({ success: false, message: "Unable to register" }); } }
async function Login(req, res) { try { const email = String(req.body.email || "").trim().toLowerCase(); const user = await User.findOne({ email }).select("+password"); if (!user || !(await bcrypt.compare(String(req.body.password || ""), user.password))) return res.status(401).json({ success: false, message: "Invalid email or password" }); if (user.isBlocked) return res.status(403).json({ success: false, message: "This account is blocked" }); issueTokens(res, user); return res.json({ success: true, message: "Login successful", user: { _id: user._id, name: user.name, email: user.email, phone: user.phone, role: user.role } }); } catch { return res.status(500).json({ success: false, message: "Unable to log in" }); } }
function Logout(req, res) { res.clearCookie("accessToken", cookieBaseOptions); res.clearCookie("refreshToken", cookieBaseOptions); return res.json({ success: true, message: "Logout successful" }); }
async function GetProfile(req, res) { const user = await User.findById(req.id).select(safeUser); return user ? res.json({ success: true, user }) : res.status(404).json({ success: false, message: "User not found" }); }
async function UpdateProfile(req, res) { const update = {}; ["name", "phone"].forEach((key) => { if (req.body[key] !== undefined) update[key] = String(req.body[key]).trim(); }); const user = await User.findByIdAndUpdate(req.id, update, { new: true }).select(safeUser); return user ? res.json({ success: true, message: "Profile updated", user }) : res.status(404).json({ success: false, message: "User not found" }); }
async function ChangePassword(req, res) { const user = await User.findById(req.id).select("+password"); if (!user || !(await bcrypt.compare(String(req.body.currentPassword || ""), user.password))) return res.status(401).json({ success: false, message: "Current password is incorrect" }); if (String(req.body.newPassword || "").length < 6) return res.status(400).json({ success: false, message: "New password must be at least 6 characters" }); user.password = await bcrypt.hash(req.body.newPassword, 10); await user.save(); return res.json({ success: true, message: "Password changed successfully" }); }
async function CreateByAdmin(req, res) { try { const { name, password, phone } = req.body; const email = String(req.body.email || "").trim().toLowerCase(); const role = req.body.role === "admin" ? "admin" : "customer"; if (!String(name || "").trim() || !validEmail(email) || String(password || "").length < 6) return res.status(400).json({ success: false, message: "Name, valid email and password are required" }); if (await User.exists({ email })) return res.status(409).json({ success: false, message: "User already exists" }); await User.create({ name: name.trim(), email, phone: String(phone || "").trim(), password: await bcrypt.hash(password, 10), role }); return res.status(201).json({ success: true, message: "User created successfully" }); } catch { return res.status(500).json({ success: false, message: "Unable to create user" }); } }
async function GetAllUsers(req, res) { const users = await User.find().select(safeUser).sort({ createdAt: -1 }); return res.json({ success: true, users }); }
async function UpdateUserByAdmin(req, res) { const update = {}; ["name", "phone", "isBlocked", "role"].forEach((key) => { if (req.body[key] !== undefined) update[key] = req.body[key]; }); if (update.role && !["customer", "admin"].includes(update.role)) delete update.role; const user = await User.findByIdAndUpdate(req.params.id, update, { new: true }).select(safeUser); return user ? res.json({ success: true, message: "User updated", user }) : res.status(404).json({ success: false, message: "User not found" }); }
async function BlockUser(req, res) { const user = await User.findOneAndUpdate({ _id: req.params.id, role: { $ne: "admin" } }, { isBlocked: true }, { new: true }).select(safeUser); return user ? res.json({ success: true, message: "User blocked", user }) : res.status(404).json({ success: false, message: "Customer not found" }); }
async function UnblockUser(req, res) { const user = await User.findOneAndUpdate({ _id: req.params.id, role: { $ne: "admin" } }, { isBlocked: false }, { new: true }).select(safeUser); return user ? res.json({ success: true, message: "User unblocked", user }) : res.status(404).json({ success: false, message: "Customer not found" }); }
module.exports = { SignUp, Login, Logout, GetProfile, UpdateProfile, ChangePassword, CreateByAdmin, GetAllUsers, UpdateUserByAdmin, BlockUser, UnblockUser };
